/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimalCard: typeof import('./components/AnimalCard.vue')['default']
    AnimalCarousel: typeof import('./components/AnimalCarousel.vue')['default']
    AnimalPhotoUploader: typeof import('./components/common/AnimalPhotoUploader.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppNavbar: typeof import('./components/navigation/AppNavbar.vue')['default']
    AvatarIcon: typeof import('./components/AvatarIcon.vue')['default']
    BaseDatePicker: typeof import('./components/common/BaseDatePicker.vue')['default']
    DesktopNavbar: typeof import('./components/navigation/DesktopNavbar.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    HowToSection: typeof import('./components/sections/HowToSection.vue')['default']
    JoinUsSection: typeof import('./components/sections/JoinUsSection.vue')['default']
    LeafletMap: typeof import('./components/LeafletMap.vue')['default']
    MobileNavbar: typeof import('./components/navigation/MobileNavbar.vue')['default']
    PageWrapper: typeof import('./components/PageWrapper.vue')['default']
    PetsSection: typeof import('./components/sections/PetsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsSection: typeof import('./components/sections/StatsSection.vue')['default']
    StoriesSection: typeof import('./components/sections/StoriesSection.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
    VisitUsSection: typeof import('./components/sections/VisitUsSection.vue')['default']
  }
}
