/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    HowToSection: typeof import('./components/sections/HowToSection.vue')['default']
    JoinUsSection: typeof import('./components/sections/JoinUsSection.vue')['default']
    LeafletMap: typeof import('./components/LeafletMap.vue')['default']
    PetsSection: typeof import('./components/sections/PetsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsSection: typeof import('./components/sections/StatsSection.vue')['default']
    StoriesSection: typeof import('./components/sections/StoriesSection.vue')['default']
    VisitUsSection: typeof import('./components/sections/VisitUsSection.vue')['default']
  }
}
